name: Bilbao Test

on:
  schedule:
    # Run weekly on Mondays at 5:00 AM UTC
    - cron: '0 5 * * 1'
  workflow_dispatch:

# Default to bash
defaults:
  run:
    shell: bash

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: set up pixi
      uses: prefix-dev/setup-pixi@v0.8.1
      with:
          manifest-path: pixi/pixi.toml

    - name: Install GSAS-II with pixi
      run: |
          cd pixi
          pixi run install 

    - name: diagnose GSAS-II issues
      run: |
          cd pixi
          pixi run python -c "import GSASII"
          pixi run python -c "import GSASII.pyspg; print(GSASII.pyspg.__file__)"
          pixi run python -c "from GSASII import GSASIIspc as G2spc; G2spc.SpcGroup('R 3 C r')"

    - name: run Bilbao self-test
      run: |
          cd pixi
          pixi run python -m pytest ../tests/run_bilbao.py
          
#    - name: run Bilbao self-test
#      run: |
#          cd tests
#          pixi run --manifest-path ../pixi/pixi.toml python -m pytest run_bilbao.py
