name: Self-Test Bilbao access routines

on:
  schedule:
    # Run weekly on Mondays at 5:00 AM UTC
    - cron: '0 5 * * 1'
  workflow_dispatch:

# Default to bash
defaults:
  run:
    shell: bash

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: set up pixi
      uses: prefix-dev/setup-pixi@v0.8.1
      with:
          manifest-path: pixi/pixi.toml

    - name: Use pixi to install GSAS-II
      run: |
          cd pixi
          pixi run install 

    - name: run Bilbao self-test
      run: |
          cd pixi
          pixi run python -m pytest ../tests/run_bilbao.py
