name: install self-installer on Windows

on:
  workflow_dispatch:    # Allows running this workflow manually
  # Runs on pushes targeting the default branch
  push:
    branches-ignore:
      - master
  #   branches: ['main']
#  pull_request:
#    branches: ['main']


jobs:
  test-GSAS-II:
    #strategy:
    #  fail-fast: false
    runs-on: 'windows-latest'
    steps:
      - uses: suisei-cn/actions-download-file@818d6b7dc8fe73f2f924b6241f2b1134ca1377d9 # 1.6.0
        id: downloadfile
        name: Download the file
        with:
          url: "https://github.com/AdvancedPhotonSource/GSAS-II-buildtools/releases/download/v1.0.1/gsas2new-5804-Windows-x86_64.exe"
          #target: download/
      #- name: find it
      #  shell: bash
      #  run: |
      #    ls -R

      - name: GSAS-II install
        shell: pwsh
        run: Start-Process -FilePath .\gsas2new-5804-Windows-x86_64.exe -ArgumentList "/S /AddToPath=1 " -NoNewWindow -Wait

      #- name: find install
      #  if: always()
      #  shell: bash
      #  run: |
      #    ls -R
          
      - name: GSAS-II find GSAS-II
        if: always()
        shell: bash
        run: |
          cd c:/ProgramData/gsas2new/GSAS-II
          ls

      - name: try all tests
        if: always()
        shell: cmd
        run: |
          call c:\ProgramData\gsas2new\Scripts\activate
          where python
          python -VV
          call conda install -y pytest
          cd c:\ProgramData\gsas2new\GSAS-II
          python -m pytest

      #     #python -v -c "import sys; print(sys.path)"
      #     python -c "import pyspg"

      # - name: try ldd
      #   if: always()
      #   shell: bash -el {0}
      #   run: |
      #     #conda create -n ntldd python=3.12 numpy=2.2 m2w64-ntldd-git
      #     conda create -n ntldd python=3.11 numpy=1.26 m2w64-ntldd-git
      #     conda activate ntldd
      #     cd GSAS-II/GSASII-bin/win_64_p3.11_n1.26
      #     #cd GSAS-II/GSASII-bin/win_64_p3.12_n2.2
      #     ls
      #     ntldd *.pyd
      #     python -c "import pyspg"
